### ISSUE TITLE
ImportError: cannot import name 'json' from 'itsdangerous'

### ISSUE THREAD

**Issue by rafaeloliveiraext** [pallets/itsdangerous#291]
Environment:

- Python version: 3.8.10, but 3.7 is affected too
- ItsDangerous version: 2.1.0

After upgrade the lib to 2.1.0 version, the lib show the error: ImportError: cannot import name 'json' from 'itsdangerous'
I'm using python 3.8.10, but in 3.7 version doesn't work too.

**Comment by pedrogomesesfera** [comment]
Should the line `from ._json import json` have been remove from file `src/itsdangerous/__init__.py` on commit 506ca21d8cc1d16313270c37b6990c9e7762f68e ? It is breaking some libs which I use as well

**Comment by davidism** [comment]
Duplicate of #289 

You are using an unsupported version of Flask, please update to the latest version if possible. Additionally, please read https://hynek.me/articles/semver-will-not-save-you/, then use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.
